import React, { useState } from 'react';
import { 
  BookOpen, 
  Download, 
  Copy, 
  Check, 
  Search, 
  ExternalLink, 
  Code2, 
  FileText, 
  Folder, 
  Send,
  Layers,
  ChevronDown,
  ChevronRight
} from 'lucide-react';
import { Collection, ApiRequest, Variable } from '../../types';
import { generateCodeByVariant } from '../../services/codeGenService';

interface CollectionDocsViewerProps {
  collections: Collection[];
  activeCollectionId?: string;
  variables?: Variable[];
  onOpenRequestInStudio?: (req: ApiRequest) => void;
}

type SnippetLang = 'curl' | 'js-fetch' | 'js-axios' | 'python-requests' | 'php-curl' | 'go-native' | 'csharp-httpclient';

export const CollectionDocsViewer: React.FC<CollectionDocsViewerProps> = ({
  collections,
  activeCollectionId,
  variables = [],
  onOpenRequestInStudio,
}) => {
  const [selectedColId, setSelectedColId] = useState<string>(
    activeCollectionId || collections[0]?.id || ''
  );
  const [searchQuery, setSearchQuery] = useState('');
  const [activeSnippetLang, setActiveSnippetLang] = useState<SnippetLang>('curl');
  const [copiedCodeId, setCopiedCodeId] = useState<string | null>(null);

  const selectedCol = collections.find(c => c.id === selectedColId) || collections[0];

  // Flatten all requests with optional folder name
  const allRequests: { request: ApiRequest; folderName?: string }[] = [];
  if (selectedCol) {
    selectedCol.requests.forEach(r => allRequests.push({ request: r }));
    selectedCol.folders.forEach(f => {
      f.requests.forEach(r => allRequests.push({ request: r, folderName: f.name }));
    });
  }

  const filtered = allRequests.filter(item => {
    if (!searchQuery.trim()) return true;
    const q = searchQuery.toLowerCase();
    return (
      item.request.name.toLowerCase().includes(q) ||
      item.request.url.toLowerCase().includes(q) ||
      item.request.method.toLowerCase().includes(q) ||
      (item.folderName && item.folderName.toLowerCase().includes(q))
    );
  });

  const handleCopy = (code: string, id: string) => {
    navigator.clipboard.writeText(code);
    setCopiedCodeId(id);
    setTimeout(() => setCopiedCodeId(null), 2000);
  };

  const handleExportMarkdown = () => {
    if (!selectedCol) return;
    let md = `# ${selectedCol.name} - API Documentation\n\n`;
    md += `${selectedCol.description || 'Interactive API documentation generated by CloudPost.'}\n\n`;
    md += `Base URL: \`${variables.find(v => v.key === 'baseUrl')?.value || 'https://api.example.com'}\`\n\n`;
    md += `---\n\n`;

    filtered.forEach(({ request, folderName }) => {
      md += `## [${request.method}] ${request.name}\n\n`;
      if (folderName) md += `*Folder: ${folderName}*\n\n`;
      md += `**Endpoint:** \`${request.method} ${request.url}\`\n\n`;
      if (request.description) md += `${request.description}\n\n`;

      if (request.params.filter(p => p.enabled).length > 0) {
        md += `### Query Parameters\n\n| Parameter | Value | Description |\n|---|---|---|\n`;
        request.params.filter(p => p.enabled).forEach(p => {
          md += `| \`${p.key}\` | \`${p.value}\` | ${p.description || '-'} |\n`;
        });
        md += `\n`;
      }

      if (request.headers.filter(h => h.enabled).length > 0) {
        md += `### Headers\n\n| Header | Value |\n|---|---|\n`;
        request.headers.filter(h => h.enabled).forEach(h => {
          md += `| \`${h.key}\` | \`${h.value}\` |\n`;
        });
        md += `\n`;
      }

      const snippet = generateCodeByVariant(activeSnippetLang, request, variables);
      md += `### Code Example (${activeSnippetLang})\n\n\`\`\`\n${snippet}\n\`\`\`\n\n---\n\n`;
    });

    const blob = new Blob([md], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${selectedCol.name.toLowerCase().replace(/\s+/g, '_')}_docs.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleExportHtml = () => {
    if (!selectedCol) return;
    let content = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>${selectedCol.name} - API Reference</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: #0e111a; color: #e2e8f0; margin: 0; padding: 40px 20px; line-height: 1.6; }
    .container { max-width: 900px; margin: 0 auto; }
    h1 { color: #f97316; font-size: 2rem; margin-bottom: 8px; }
    .card { background: #161922; border: 1px solid rgba(255,255,255,0.1); border-radius: 12px; padding: 24px; margin-bottom: 24px; }
    .method { display: inline-block; padding: 4px 10px; border-radius: 6px; font-weight: bold; font-size: 0.8rem; margin-right: 8px; font-family: monospace; }
    .GET { background: rgba(16,185,129,0.2); color: #10b981; }
    .POST { background: rgba(249,115,22,0.2); color: #f97316; }
    .PUT { background: rgba(59,130,246,0.2); color: #3b82f6; }
    .DELETE { background: rgba(244,63,94,0.2); color: #f43f5e; }
    pre { background: #090b10; padding: 16px; border-radius: 8px; overflow-x: auto; font-family: monospace; font-size: 0.85rem; color: #cbd5e1; }
    table { width: 100%; border-collapse: collapse; margin-top: 12px; margin-bottom: 16px; }
    th, td { text-align: left; padding: 8px 12px; border-bottom: 1px solid rgba(255,255,255,0.06); font-size: 0.85rem; }
    th { color: #94a3b8; }
  </style>
</head>
<body>
  <div class="container">
    <h1>${selectedCol.name}</h1>
    <p>${selectedCol.description || 'API Reference documentation generated by CloudPost.'}</p>
    <hr style="border-color: rgba(255,255,255,0.1); margin: 24px 0;">
`;

    filtered.forEach(({ request, folderName }) => {
      const snippet = generateCodeByVariant('curl', request, variables);
      content += `
    <div class="card">
      <div style="margin-bottom: 12px;">
        <span class="method ${request.method}">${request.method}</span>
        <strong style="font-size: 1.1rem;">${request.name}</strong>
        ${folderName ? `<span style="color: #64748b; font-size: 0.85rem; margin-left: 8px;">in ${folderName}</span>` : ''}
      </div>
      <div style="font-family: monospace; font-size: 0.9rem; color: #94a3b8; margin-bottom: 16px; word-break: break-all;">
        ${request.url}
      </div>
      ${request.description ? `<p style="font-size: 0.9rem; color: #94a3b8;">${request.description}</p>` : ''}
      <h4>cURL Example</h4>
      <pre>${snippet.replace(/</g, '&lt;').replace(/>/g, '&gt;')}</pre>
    </div>`;
    });

    content += `
  </div>
</body>
</html>`;

    const blob = new Blob([content], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${selectedCol.name.toLowerCase().replace(/\s+/g, '_')}_docs.html`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const getMethodBadgeClass = (method: string) => {
    switch (method.toUpperCase()) {
      case 'GET': return 'bg-emerald-500/20 text-emerald-400 border-emerald-500/30';
      case 'POST': return 'bg-orange-500/20 text-orange-400 border-orange-500/30';
      case 'PUT': return 'bg-blue-500/20 text-blue-400 border-blue-500/30';
      case 'DELETE': return 'bg-rose-500/20 text-rose-400 border-rose-500/30';
      case 'PATCH': return 'bg-amber-500/20 text-amber-400 border-amber-500/30';
      default: return 'bg-zinc-500/20 text-zinc-400 border-zinc-500/30';
    }
  };

  return (
    <div id="collection-docs-viewer" className="flex flex-col h-full bg-[#0d1017] text-zinc-100 select-text overflow-hidden">
      {/* Top Controls Toolbar */}
      <div className="p-4 bg-[#141722] border-b border-white/10 shrink-0 flex flex-wrap items-center justify-between gap-3 shadow-md">
        <div className="flex items-center gap-3">
          <div className="flex items-center gap-2">
            <BookOpen className="w-5 h-5 text-orange-400" />
            <h2 className="text-base font-bold text-white">API Reference Documentation</h2>
          </div>

          {/* Collection Selector */}
          <select
            value={selectedColId}
            onChange={e => setSelectedColId(e.target.value)}
            className="bg-[#0d1017] border border-white/10 rounded-lg px-3 py-1.5 text-xs text-zinc-200 focus:outline-none focus:border-orange-500"
          >
            {collections.map(c => (
              <option key={c.id} value={c.id}>
                Collection: {c.name} ({c.requests.length + c.folders.reduce((acc, f) => acc + f.requests.length, 0)} endpoints)
              </option>
            ))}
          </select>
        </div>

        <div className="flex items-center gap-2">
          {/* Search box */}
          <div className="flex items-center bg-[#0d1017] border border-white/10 rounded-lg px-2.5 py-1 text-xs">
            <Search className="w-3.5 h-3.5 text-zinc-500 mr-2" />
            <input
              type="text"
              value={searchQuery}
              onChange={e => setSearchQuery(e.target.value)}
              placeholder="Search endpoints..."
              className="bg-transparent text-xs text-zinc-200 focus:outline-none w-36 sm:w-48"
            />
          </div>

          <button
            type="button"
            onClick={handleExportHtml}
            className="px-3 py-1.5 bg-white/5 hover:bg-white/10 border border-white/10 text-xs font-medium rounded-lg flex items-center gap-1.5 transition-colors"
            title="Download complete standalone HTML documentation file"
          >
            <Download className="w-3.5 h-3.5" />
            <span>Export HTML</span>
          </button>

          <button
            type="button"
            onClick={handleExportMarkdown}
            className="px-3 py-1.5 bg-orange-600 hover:bg-orange-500 text-white text-xs font-semibold rounded-lg flex items-center gap-1.5 transition-colors shadow-md shadow-orange-600/20"
            title="Download README Markdown document"
          >
            <FileText className="w-3.5 h-3.5" />
            <span>Export Markdown</span>
          </button>
        </div>
      </div>

      {/* Main Content Area */}
      <div className="flex-1 overflow-y-auto p-4 sm:p-6 max-w-6xl w-full mx-auto space-y-6">
        {/* Collection Header Banner */}
        {selectedCol && (
          <div className="p-6 bg-[#131620] border border-white/10 rounded-2xl shadow-xl">
            <h1 className="text-2xl font-black text-white tracking-tight mb-2 flex items-center gap-3">
              <span>{selectedCol.name}</span>
              <span className="text-xs font-normal px-2.5 py-1 bg-white/5 border border-white/10 rounded-full text-zinc-400 font-mono">
                {allRequests.length} Endpoints
              </span>
            </h1>
            <p className="text-xs text-zinc-400 leading-relaxed max-w-3xl mb-4">
              {selectedCol.description || 'Production API endpoints, query schemas, authentication parameters, and multi-language client SDK examples.'}
            </p>

            {/* Language Code Snippet Picker */}
            <div className="flex items-center gap-2 pt-3 border-t border-white/5 overflow-x-auto text-xs">
              <span className="text-zinc-500 text-[11px] font-semibold uppercase tracking-wider shrink-0">
                Code Snippet Language:
              </span>
              {[
                { id: 'curl', label: 'cURL' },
                { id: 'js-fetch', label: 'JS Fetch' },
                { id: 'js-axios', label: 'Axios' },
                { id: 'python-requests', label: 'Python' },
                { id: 'php-curl', label: 'PHP' },
                { id: 'go-native', label: 'Go' },
                { id: 'csharp-httpclient', label: 'C#' },
              ].map(lang => (
                <button
                  key={lang.id}
                  onClick={() => setActiveSnippetLang(lang.id as SnippetLang)}
                  className={`px-2.5 py-1 rounded-md text-[11px] font-medium transition-colors whitespace-nowrap ${
                    activeSnippetLang === lang.id
                      ? 'bg-orange-500/20 text-orange-400 border border-orange-500/30'
                      : 'text-zinc-400 hover:text-white hover:bg-white/5'
                  }`}
                >
                  {lang.label}
                </button>
              ))}
            </div>
          </div>
        )}

        {/* Endpoints List */}
        <div className="space-y-6">
          {filtered.map(({ request, folderName }) => {
            const snippet = generateCodeByVariant(activeSnippetLang, request, variables);
            const isCopied = copiedCodeId === request.id;

            return (
              <div
                key={request.id}
                className="bg-[#131620] border border-white/10 hover:border-white/20 rounded-2xl overflow-hidden shadow-lg transition-all"
              >
                {/* Endpoint Header Bar */}
                <div className="p-4 bg-[#181c28] border-b border-white/5 flex flex-wrap items-center justify-between gap-3">
                  <div className="flex items-center gap-2.5 flex-1 min-w-0">
                    <span className={`px-2.5 py-1 text-xs font-mono font-bold rounded-md border uppercase ${getMethodBadgeClass(request.method)}`}>
                      {request.method}
                    </span>
                    <span className="font-semibold text-sm text-white truncate">
                      {request.name}
                    </span>
                    {folderName && (
                      <span className="px-2 py-0.5 bg-white/5 border border-white/5 text-[11px] text-zinc-400 rounded flex items-center gap-1">
                        <Folder className="w-3 h-3 text-amber-400" />
                        {folderName}
                      </span>
                    )}
                  </div>

                  <div className="flex items-center gap-2">
                    {onOpenRequestInStudio && (
                      <button
                        type="button"
                        onClick={() => onOpenRequestInStudio(request)}
                        className="px-3 py-1 bg-white/5 hover:bg-white/10 text-xs text-orange-400 hover:text-orange-300 rounded-lg flex items-center gap-1.5 transition-colors border border-white/10"
                        title="Open in Request Builder"
                      >
                        <Send className="w-3 h-3" />
                        <span>Run in Studio</span>
                      </button>
                    )}
                  </div>
                </div>

                {/* Endpoint URL & Description */}
                <div className="p-4 border-b border-white/5 space-y-2">
                  <div className="flex items-center bg-[#0a0c12] border border-white/5 rounded-lg px-3 py-2 font-mono text-xs text-zinc-300 break-all">
                    <span className="text-zinc-500 mr-2 uppercase select-none">{request.method}</span>
                    <span className="text-orange-300">{request.url}</span>
                  </div>

                  {request.description && (
                    <p className="text-xs text-zinc-400 leading-relaxed pt-1">
                      {request.description}
                    </p>
                  )}
                </div>

                {/* Parameters & Headers Specs */}
                {(request.params.some(p => p.enabled) || request.headers.some(h => h.enabled)) && (
                  <div className="p-4 border-b border-white/5 grid grid-cols-1 md:grid-cols-2 gap-4 text-xs">
                    {request.params.some(p => p.enabled) && (
                      <div>
                        <h4 className="font-semibold text-zinc-300 mb-2">Query Parameters</h4>
                        <div className="bg-[#090b10] border border-white/5 rounded-lg overflow-hidden">
                          <table className="w-full text-left">
                            <thead className="bg-white/5 text-zinc-400 text-[11px]">
                              <tr>
                                <th className="p-2">Key</th>
                                <th className="p-2">Default Value</th>
                              </tr>
                            </thead>
                            <tbody className="divide-y divide-white/5 text-[11px] font-mono">
                              {request.params.filter(p => p.enabled).map((p, idx) => (
                                <tr key={idx}>
                                  <td className="p-2 text-cyan-300">{p.key}</td>
                                  <td className="p-2 text-zinc-400">{p.value || '-'}</td>
                                </tr>
                              ))}
                            </tbody>
                          </table>
                        </div>
                      </div>
                    )}

                    {request.headers.some(h => h.enabled) && (
                      <div>
                        <h4 className="font-semibold text-zinc-300 mb-2">Headers</h4>
                        <div className="bg-[#090b10] border border-white/5 rounded-lg overflow-hidden">
                          <table className="w-full text-left">
                            <thead className="bg-white/5 text-zinc-400 text-[11px]">
                              <tr>
                                <th className="p-2">Header</th>
                                <th className="p-2">Value</th>
                              </tr>
                            </thead>
                            <tbody className="divide-y divide-white/5 text-[11px] font-mono">
                              {request.headers.filter(h => h.enabled).map((h, idx) => (
                                <tr key={idx}>
                                  <td className="p-2 text-emerald-300">{h.key}</td>
                                  <td className="p-2 text-zinc-400">{h.value || '-'}</td>
                                </tr>
                              ))}
                            </tbody>
                          </table>
                        </div>
                      </div>
                    )}
                  </div>
                )}

                {/* Live Code Snippet Box */}
                <div className="p-4 bg-[#0d1017]">
                  <div className="flex items-center justify-between mb-2">
                    <span className="text-xs text-zinc-400 font-medium flex items-center gap-1.5">
                      <Code2 className="w-3.5 h-3.5 text-orange-400" />
                      Client Request Example ({activeSnippetLang})
                    </span>
                    <button
                      type="button"
                      onClick={() => handleCopy(snippet, request.id)}
                      className="text-xs text-zinc-400 hover:text-white flex items-center gap-1 bg-white/5 hover:bg-white/10 px-2.5 py-1 rounded transition-colors"
                    >
                      {isCopied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
                      <span>{isCopied ? 'Copied' : 'Copy'}</span>
                    </button>
                  </div>
                  <pre className="p-3 bg-[#08090f] text-zinc-300 rounded-lg border border-white/5 text-xs font-mono overflow-x-auto leading-relaxed">
                    {snippet}
                  </pre>
                </div>
              </div>
            );
          })}
        </div>
      </div>
    </div>
  );
};
